version: "3"

tasks:
  dev:
    cmds:
      - air

  server:
    cmds:
      - go run ./examples/server .

  client-desktop:
    cmds:
      - go run ./examples/ebiten-client-desktop .

  gomp-server:
    cmds:
      - go run ./pkg/ebiten-ecs/examples/gomp-server .

  gomp-client:
    cmds:
      - go run ./pkg/ebiten-ecs/examples/gomp-ebiten-client .

  build-web-client:
    cmds:
      - env GOOS=js GOARCH=wasm go build -o ./.dist/web-ebiten-client.wasm ./examples/web-ebiten-client-ws/main.go
      - cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./.dist

  proto:
    cmds:
      - protoc --go_out=. internal/**/*.proto

  pprof:
    cmds:
      - go tool pprof -http=":8000" 'http://localhost:3000/debug/pprof/profile?seconds=10'

  pprof-cpu:
    cmds:
      - go tool pprof -http=":8000" ./cpu.out
