//
//This Source Code Form is subject to the terms of the Mozilla
//Public License, v. 2.0. If a copy of the MPL was not distributed
//with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: internal/protos/ability.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbilityCostType int32

const (
	AbilityCostType_none AbilityCostType = 0
	AbilityCostType_mana AbilityCostType = 1
	AbilityCostType_hp   AbilityCostType = 2
)

// Enum value maps for AbilityCostType.
var (
	AbilityCostType_name = map[int32]string{
		0: "none",
		1: "mana",
		2: "hp",
	}
	AbilityCostType_value = map[string]int32{
		"none": 0,
		"mana": 1,
		"hp":   2,
	}
)

func (x AbilityCostType) Enum() *AbilityCostType {
	p := new(AbilityCostType)
	*p = x
	return p
}

func (x AbilityCostType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AbilityCostType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protos_ability_proto_enumTypes[0].Descriptor()
}

func (AbilityCostType) Type() protoreflect.EnumType {
	return &file_internal_protos_ability_proto_enumTypes[0]
}

func (x AbilityCostType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AbilityCostType.Descriptor instead.
func (AbilityCostType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{0}
}

type AbilityTargetType int32

const (
	AbilityTargetType_no_target AbilityTargetType = 0
	AbilityTargetType_unit      AbilityTargetType = 1
	AbilityTargetType_aoe       AbilityTargetType = 2
	AbilityTargetType_point     AbilityTargetType = 3
	AbilityTargetType_skillshot AbilityTargetType = 4
	AbilityTargetType_global    AbilityTargetType = 5
)

// Enum value maps for AbilityTargetType.
var (
	AbilityTargetType_name = map[int32]string{
		0: "no_target",
		1: "unit",
		2: "aoe",
		3: "point",
		4: "skillshot",
		5: "global",
	}
	AbilityTargetType_value = map[string]int32{
		"no_target": 0,
		"unit":      1,
		"aoe":       2,
		"point":     3,
		"skillshot": 4,
		"global":    5,
	}
)

func (x AbilityTargetType) Enum() *AbilityTargetType {
	p := new(AbilityTargetType)
	*p = x
	return p
}

func (x AbilityTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AbilityTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protos_ability_proto_enumTypes[1].Descriptor()
}

func (AbilityTargetType) Type() protoreflect.EnumType {
	return &file_internal_protos_ability_proto_enumTypes[1]
}

func (x AbilityTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AbilityTargetType.Descriptor instead.
func (AbilityTargetType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{1}
}

type AbilityType int32

const (
	AbilityType_passive AbilityType = 0
	AbilityType_active  AbilityType = 1
	AbilityType_toggle  AbilityType = 2
)

// Enum value maps for AbilityType.
var (
	AbilityType_name = map[int32]string{
		0: "passive",
		1: "active",
		2: "toggle",
	}
	AbilityType_value = map[string]int32{
		"passive": 0,
		"active":  1,
		"toggle":  2,
	}
)

func (x AbilityType) Enum() *AbilityType {
	p := new(AbilityType)
	*p = x
	return p
}

func (x AbilityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AbilityType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protos_ability_proto_enumTypes[2].Descriptor()
}

func (AbilityType) Type() protoreflect.EnumType {
	return &file_internal_protos_ability_proto_enumTypes[2]
}

func (x AbilityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AbilityType.Descriptor instead.
func (AbilityType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{2}
}

type Effect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Effect) Reset() {
	*x = Effect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{0}
}

func (x *Effect) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AbilityCost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  AbilityCostType `protobuf:"varint,1,opt,name=type,proto3,enum=abilities.AbilityCostType" json:"type,omitempty"`
	Value uint32          `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AbilityCost) Reset() {
	*x = AbilityCost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityCost) ProtoMessage() {}

func (x *AbilityCost) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityCost.ProtoReflect.Descriptor instead.
func (*AbilityCost) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{1}
}

func (x *AbilityCost) GetType() AbilityCostType {
	if x != nil {
		return x.Type
	}
	return AbilityCostType_none
}

func (x *AbilityCost) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AbilityTargetUnitData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbilityTargetUnitData) Reset() {
	*x = AbilityTargetUnitData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityTargetUnitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityTargetUnitData) ProtoMessage() {}

func (x *AbilityTargetUnitData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityTargetUnitData.ProtoReflect.Descriptor instead.
func (*AbilityTargetUnitData) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{2}
}

type AbilityTargetAoeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Range  uint32 `protobuf:"varint,1,opt,name=range,proto3" json:"range,omitempty"`
	Radius uint32 `protobuf:"varint,2,opt,name=radius,proto3" json:"radius,omitempty"`
}

func (x *AbilityTargetAoeData) Reset() {
	*x = AbilityTargetAoeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityTargetAoeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityTargetAoeData) ProtoMessage() {}

func (x *AbilityTargetAoeData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityTargetAoeData.ProtoReflect.Descriptor instead.
func (*AbilityTargetAoeData) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{3}
}

func (x *AbilityTargetAoeData) GetRange() uint32 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *AbilityTargetAoeData) GetRadius() uint32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type AbilityTargetPointData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbilityTargetPointData) Reset() {
	*x = AbilityTargetPointData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityTargetPointData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityTargetPointData) ProtoMessage() {}

func (x *AbilityTargetPointData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityTargetPointData.ProtoReflect.Descriptor instead.
func (*AbilityTargetPointData) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{4}
}

type AbilityTargetSkillshotData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbilityTargetSkillshotData) Reset() {
	*x = AbilityTargetSkillshotData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityTargetSkillshotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityTargetSkillshotData) ProtoMessage() {}

func (x *AbilityTargetSkillshotData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityTargetSkillshotData.ProtoReflect.Descriptor instead.
func (*AbilityTargetSkillshotData) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{5}
}

type AbilityTargetGlobalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbilityTargetGlobalData) Reset() {
	*x = AbilityTargetGlobalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityTargetGlobalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityTargetGlobalData) ProtoMessage() {}

func (x *AbilityTargetGlobalData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityTargetGlobalData.ProtoReflect.Descriptor instead.
func (*AbilityTargetGlobalData) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{6}
}

type AbilityTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type AbilityTargetType `protobuf:"varint,1,opt,name=type,proto3,enum=abilities.AbilityTargetType" json:"type,omitempty"`
	// Types that are assignable to Data:
	//
	//	*AbilityTarget_Unit
	//	*AbilityTarget_Aoe
	//	*AbilityTarget_Point
	//	*AbilityTarget_Skillshot
	//	*AbilityTarget_Global
	Data isAbilityTarget_Data `protobuf_oneof:"data"`
}

func (x *AbilityTarget) Reset() {
	*x = AbilityTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityTarget) ProtoMessage() {}

func (x *AbilityTarget) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityTarget.ProtoReflect.Descriptor instead.
func (*AbilityTarget) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{7}
}

func (x *AbilityTarget) GetType() AbilityTargetType {
	if x != nil {
		return x.Type
	}
	return AbilityTargetType_no_target
}

func (m *AbilityTarget) GetData() isAbilityTarget_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *AbilityTarget) GetUnit() *AbilityTargetUnitData {
	if x, ok := x.GetData().(*AbilityTarget_Unit); ok {
		return x.Unit
	}
	return nil
}

func (x *AbilityTarget) GetAoe() *AbilityTargetAoeData {
	if x, ok := x.GetData().(*AbilityTarget_Aoe); ok {
		return x.Aoe
	}
	return nil
}

func (x *AbilityTarget) GetPoint() *AbilityTargetPointData {
	if x, ok := x.GetData().(*AbilityTarget_Point); ok {
		return x.Point
	}
	return nil
}

func (x *AbilityTarget) GetSkillshot() *AbilityTargetSkillshotData {
	if x, ok := x.GetData().(*AbilityTarget_Skillshot); ok {
		return x.Skillshot
	}
	return nil
}

func (x *AbilityTarget) GetGlobal() *AbilityTargetGlobalData {
	if x, ok := x.GetData().(*AbilityTarget_Global); ok {
		return x.Global
	}
	return nil
}

type isAbilityTarget_Data interface {
	isAbilityTarget_Data()
}

type AbilityTarget_Unit struct {
	Unit *AbilityTargetUnitData `protobuf:"bytes,2,opt,name=unit,proto3,oneof"`
}

type AbilityTarget_Aoe struct {
	Aoe *AbilityTargetAoeData `protobuf:"bytes,3,opt,name=aoe,proto3,oneof"`
}

type AbilityTarget_Point struct {
	Point *AbilityTargetPointData `protobuf:"bytes,4,opt,name=point,proto3,oneof"`
}

type AbilityTarget_Skillshot struct {
	Skillshot *AbilityTargetSkillshotData `protobuf:"bytes,5,opt,name=skillshot,proto3,oneof"`
}

type AbilityTarget_Global struct {
	Global *AbilityTargetGlobalData `protobuf:"bytes,6,opt,name=global,proto3,oneof"`
}

func (*AbilityTarget_Unit) isAbilityTarget_Data() {}

func (*AbilityTarget_Aoe) isAbilityTarget_Data() {}

func (*AbilityTarget_Point) isAbilityTarget_Data() {}

func (*AbilityTarget_Skillshot) isAbilityTarget_Data() {}

func (*AbilityTarget_Global) isAbilityTarget_Data() {}

type AbilityMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CasterId    *uint32        `protobuf:"varint,2,opt,name=caster_id,json=casterId,proto3,oneof" json:"caster_id,omitempty"`
	Type        AbilityType    `protobuf:"varint,3,opt,name=type,proto3,enum=abilities.AbilityType" json:"type,omitempty"`
	CooldownMs  uint32         `protobuf:"varint,4,opt,name=cooldown_ms,json=cooldownMs,proto3" json:"cooldown_ms,omitempty"`
	Cost        *AbilityCost   `protobuf:"bytes,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Target      *AbilityTarget `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Effects     []*Effect      `protobuf:"bytes,7,rep,name=effects,proto3" json:"effects,omitempty"`
	SideEffects []*Effect      `protobuf:"bytes,8,rep,name=side_effects,json=sideEffects,proto3" json:"side_effects,omitempty"`
	Name        string         `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Description string         `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AbilityMsg) Reset() {
	*x = AbilityMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_ability_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityMsg) ProtoMessage() {}

func (x *AbilityMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_ability_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityMsg.ProtoReflect.Descriptor instead.
func (*AbilityMsg) Descriptor() ([]byte, []int) {
	return file_internal_protos_ability_proto_rawDescGZIP(), []int{8}
}

func (x *AbilityMsg) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AbilityMsg) GetCasterId() uint32 {
	if x != nil && x.CasterId != nil {
		return *x.CasterId
	}
	return 0
}

func (x *AbilityMsg) GetType() AbilityType {
	if x != nil {
		return x.Type
	}
	return AbilityType_passive
}

func (x *AbilityMsg) GetCooldownMs() uint32 {
	if x != nil {
		return x.CooldownMs
	}
	return 0
}

func (x *AbilityMsg) GetCost() *AbilityCost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *AbilityMsg) GetTarget() *AbilityTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AbilityMsg) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *AbilityMsg) GetSideEffects() []*Effect {
	if x != nil {
		return x.SideEffects
	}
	return nil
}

func (x *AbilityMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AbilityMsg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_internal_protos_ability_proto protoreflect.FileDescriptor

var file_internal_protos_ability_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x18, 0x0a, 0x06, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x0b, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x43,
	0x6f, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x44, 0x0a, 0x14, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x41, 0x6f, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x1c, 0x0a, 0x1a, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x68, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x19, 0x0a, 0x17, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0xf6, 0x02, 0x0a, 0x0d,
	0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x30, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x36, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48,
	0x00, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x33, 0x0a, 0x03, 0x61, 0x6f, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x6f,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6f, 0x65, 0x12, 0x39, 0x0a, 0x05,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x68, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x68, 0x6f, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x3c,
	0x0a, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x90, 0x03, 0x0a, 0x0a, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x08, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x6d, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77, 0x6e,
	0x4d, 0x73, 0x12, 0x2a, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x2b, 0x0a, 0x07, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x52, 0x07, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x12, 0x34, 0x0a,
	0x0c, 0x73, 0x69, 0x64, 0x65, 0x5f, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x0b, 0x73, 0x69, 0x64, 0x65, 0x45, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x2a, 0x2d, 0x0a, 0x0f, 0x41, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x43, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x6e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x10, 0x01, 0x12, 0x06,
	0x0a, 0x02, 0x68, 0x70, 0x10, 0x02, 0x2a, 0x5b, 0x0a, 0x11, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x6e,
	0x6f, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x61, 0x6f, 0x65, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x73, 0x68, 0x6f, 0x74, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x10, 0x05, 0x2a, 0x32, 0x0a, 0x0b, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x61, 0x73, 0x73, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x74,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x10, 0x02, 0x42, 0x11, 0x5a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_protos_ability_proto_rawDescOnce sync.Once
	file_internal_protos_ability_proto_rawDescData = file_internal_protos_ability_proto_rawDesc
)

func file_internal_protos_ability_proto_rawDescGZIP() []byte {
	file_internal_protos_ability_proto_rawDescOnce.Do(func() {
		file_internal_protos_ability_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_ability_proto_rawDescData)
	})
	return file_internal_protos_ability_proto_rawDescData
}

var file_internal_protos_ability_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_protos_ability_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_protos_ability_proto_goTypes = []any{
	(AbilityCostType)(0),               // 0: abilities.AbilityCostType
	(AbilityTargetType)(0),             // 1: abilities.AbilityTargetType
	(AbilityType)(0),                   // 2: abilities.AbilityType
	(*Effect)(nil),                     // 3: abilities.Effect
	(*AbilityCost)(nil),                // 4: abilities.AbilityCost
	(*AbilityTargetUnitData)(nil),      // 5: abilities.AbilityTargetUnitData
	(*AbilityTargetAoeData)(nil),       // 6: abilities.AbilityTargetAoeData
	(*AbilityTargetPointData)(nil),     // 7: abilities.AbilityTargetPointData
	(*AbilityTargetSkillshotData)(nil), // 8: abilities.AbilityTargetSkillshotData
	(*AbilityTargetGlobalData)(nil),    // 9: abilities.AbilityTargetGlobalData
	(*AbilityTarget)(nil),              // 10: abilities.AbilityTarget
	(*AbilityMsg)(nil),                 // 11: abilities.AbilityMsg
}
var file_internal_protos_ability_proto_depIdxs = []int32{
	0,  // 0: abilities.AbilityCost.type:type_name -> abilities.AbilityCostType
	1,  // 1: abilities.AbilityTarget.type:type_name -> abilities.AbilityTargetType
	5,  // 2: abilities.AbilityTarget.unit:type_name -> abilities.AbilityTargetUnitData
	6,  // 3: abilities.AbilityTarget.aoe:type_name -> abilities.AbilityTargetAoeData
	7,  // 4: abilities.AbilityTarget.point:type_name -> abilities.AbilityTargetPointData
	8,  // 5: abilities.AbilityTarget.skillshot:type_name -> abilities.AbilityTargetSkillshotData
	9,  // 6: abilities.AbilityTarget.global:type_name -> abilities.AbilityTargetGlobalData
	2,  // 7: abilities.AbilityMsg.type:type_name -> abilities.AbilityType
	4,  // 8: abilities.AbilityMsg.cost:type_name -> abilities.AbilityCost
	10, // 9: abilities.AbilityMsg.target:type_name -> abilities.AbilityTarget
	3,  // 10: abilities.AbilityMsg.effects:type_name -> abilities.Effect
	3,  // 11: abilities.AbilityMsg.side_effects:type_name -> abilities.Effect
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_protos_ability_proto_init() }
func file_internal_protos_ability_proto_init() {
	if File_internal_protos_ability_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_ability_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Effect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_ability_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AbilityCost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_ability_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AbilityTargetUnitData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_ability_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AbilityTargetAoeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_ability_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AbilityTargetPointData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_ability_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AbilityTargetSkillshotData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_ability_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AbilityTargetGlobalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_ability_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AbilityTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_ability_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AbilityMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_protos_ability_proto_msgTypes[7].OneofWrappers = []any{
		(*AbilityTarget_Unit)(nil),
		(*AbilityTarget_Aoe)(nil),
		(*AbilityTarget_Point)(nil),
		(*AbilityTarget_Skillshot)(nil),
		(*AbilityTarget_Global)(nil),
	}
	file_internal_protos_ability_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_ability_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protos_ability_proto_goTypes,
		DependencyIndexes: file_internal_protos_ability_proto_depIdxs,
		EnumInfos:         file_internal_protos_ability_proto_enumTypes,
		MessageInfos:      file_internal_protos_ability_proto_msgTypes,
	}.Build()
	File_internal_protos_ability_proto = out.File
	file_internal_protos_ability_proto_rawDesc = nil
	file_internal_protos_ability_proto_goTypes = nil
	file_internal_protos_ability_proto_depIdxs = nil
}
