//
//This Source Code Form is subject to the terms of the Mozilla
//Public License, v. 2.0. If a copy of the MPL was not distributed
//with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: internal/protos/network-entity.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skin int32

const (
	Skin_big_demon  Skin = 0
	Skin_big_zombie Skin = 1
	Skin_elf_f      Skin = 2
)

// Enum value maps for Skin.
var (
	Skin_name = map[int32]string{
		0: "big_demon",
		1: "big_zombie",
		2: "elf_f",
	}
	Skin_value = map[string]int32{
		"big_demon":  0,
		"big_zombie": 1,
		"elf_f":      2,
	}
)

func (x Skin) Enum() *Skin {
	p := new(Skin)
	*p = x
	return p
}

func (x Skin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Skin) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protos_network_entity_proto_enumTypes[0].Descriptor()
}

func (Skin) Type() protoreflect.EnumType {
	return &file_internal_protos_network_entity_proto_enumTypes[0]
}

func (x Skin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Skin.Descriptor instead.
func (Skin) EnumDescriptor() ([]byte, []int) {
	return file_internal_protos_network_entity_proto_rawDescGZIP(), []int{0}
}

type NetworkEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32     `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Transform *Transform `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	Physics   *Physics   `protobuf:"bytes,3,opt,name=physics,proto3" json:"physics,omitempty"`
}

func (x *NetworkEntity) Reset() {
	*x = NetworkEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_network_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEntity) ProtoMessage() {}

func (x *NetworkEntity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_network_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEntity.ProtoReflect.Descriptor instead.
func (*NetworkEntity) Descriptor() ([]byte, []int) {
	return file_internal_protos_network_entity_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkEntity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NetworkEntity) GetTransform() *Transform {
	if x != nil {
		return x.Transform
	}
	return nil
}

func (x *NetworkEntity) GetPhysics() *Physics {
	if x != nil {
		return x.Physics
	}
	return nil
}

type Transform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Vector2 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Rotation float64  `protobuf:"fixed64,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Scale    *Vector2 `protobuf:"bytes,3,opt,name=Scale,proto3" json:"Scale,omitempty"`
}

func (x *Transform) Reset() {
	*x = Transform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_network_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_network_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_internal_protos_network_entity_proto_rawDescGZIP(), []int{1}
}

func (x *Transform) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Transform) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Transform) GetScale() *Vector2 {
	if x != nil {
		return x.Scale
	}
	return nil
}

type Physics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Velocity *Vector2 `protobuf:"bytes,1,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Position *Vector2 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Physics) Reset() {
	*x = Physics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_network_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Physics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Physics) ProtoMessage() {}

func (x *Physics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_network_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Physics.ProtoReflect.Descriptor instead.
func (*Physics) Descriptor() ([]byte, []int) {
	return file_internal_protos_network_entity_proto_rawDescGZIP(), []int{2}
}

func (x *Physics) GetVelocity() *Vector2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Physics) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

type PatchNetworkEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32          `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Transform *PatchTransform `protobuf:"bytes,2,opt,name=transform,proto3,oneof" json:"transform,omitempty"`
	Physics   *PatchPhysics   `protobuf:"bytes,3,opt,name=physics,proto3,oneof" json:"physics,omitempty"`
}

func (x *PatchNetworkEntity) Reset() {
	*x = PatchNetworkEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_network_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchNetworkEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchNetworkEntity) ProtoMessage() {}

func (x *PatchNetworkEntity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_network_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchNetworkEntity.ProtoReflect.Descriptor instead.
func (*PatchNetworkEntity) Descriptor() ([]byte, []int) {
	return file_internal_protos_network_entity_proto_rawDescGZIP(), []int{3}
}

func (x *PatchNetworkEntity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchNetworkEntity) GetTransform() *PatchTransform {
	if x != nil {
		return x.Transform
	}
	return nil
}

func (x *PatchNetworkEntity) GetPhysics() *PatchPhysics {
	if x != nil {
		return x.Physics
	}
	return nil
}

type PatchPhysics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Velocity *Vector2 `protobuf:"bytes,1,opt,name=velocity,proto3,oneof" json:"velocity,omitempty"`
	Position *Vector2 `protobuf:"bytes,2,opt,name=position,proto3,oneof" json:"position,omitempty"`
}

func (x *PatchPhysics) Reset() {
	*x = PatchPhysics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_network_entity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchPhysics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchPhysics) ProtoMessage() {}

func (x *PatchPhysics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_network_entity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchPhysics.ProtoReflect.Descriptor instead.
func (*PatchPhysics) Descriptor() ([]byte, []int) {
	return file_internal_protos_network_entity_proto_rawDescGZIP(), []int{4}
}

func (x *PatchPhysics) GetVelocity() *Vector2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *PatchPhysics) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

type PatchTransform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Vector2 `protobuf:"bytes,1,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Rotation *float64 `protobuf:"fixed64,2,opt,name=rotation,proto3,oneof" json:"rotation,omitempty"`
	Scale    *Vector2 `protobuf:"bytes,3,opt,name=Scale,proto3,oneof" json:"Scale,omitempty"`
}

func (x *PatchTransform) Reset() {
	*x = PatchTransform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_network_entity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchTransform) ProtoMessage() {}

func (x *PatchTransform) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_network_entity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchTransform.ProtoReflect.Descriptor instead.
func (*PatchTransform) Descriptor() ([]byte, []int) {
	return file_internal_protos_network_entity_proto_rawDescGZIP(), []int{5}
}

func (x *PatchTransform) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PatchTransform) GetRotation() float64 {
	if x != nil && x.Rotation != nil {
		return *x.Rotation
	}
	return 0
}

func (x *PatchTransform) GetScale() *Vector2 {
	if x != nil {
		return x.Scale
	}
	return nil
}

var File_internal_protos_network_entity_proto protoreflect.FileDescriptor

var file_internal_protos_network_entity_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1b,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x0d, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x29, 0x0a,
	0x07, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x52,
	0x07, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x22, 0x7b, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25,
	0x0a, 0x05, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x05,
	0x53, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x63, 0x0a, 0x07, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73,
	0x12, 0x2b, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x32, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x2b, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xae, 0x01, 0x0a, 0x12, 0x50,
	0x61, 0x74, 0x63, 0x68, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x39, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61,
	0x74, 0x63, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x48, 0x00, 0x52, 0x09,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x07,
	0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x50, 0x68, 0x79, 0x73,
	0x69, 0x63, 0x73, 0x48, 0x01, 0x52, 0x07, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x0c,
	0x50, 0x61, 0x74, 0x63, 0x68, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x12, 0x30, 0x0a, 0x08,
	0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x48,
	0x00, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x30,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x32, 0x48, 0x01, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb3, 0x01, 0x0a, 0x0e, 0x50,
	0x61, 0x74, 0x63, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x30, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32,
	0x48, 0x00, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x1f, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x48, 0x01, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x12, 0x2a, 0x0a, 0x05, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32,
	0x48, 0x02, 0x52, 0x05, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09,
	0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x53, 0x63, 0x61, 0x6c, 0x65,
	0x2a, 0x30, 0x0a, 0x04, 0x53, 0x6b, 0x69, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x62, 0x69, 0x67, 0x5f,
	0x64, 0x65, 0x6d, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x62, 0x69, 0x67, 0x5f, 0x7a,
	0x6f, 0x6d, 0x62, 0x69, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x65, 0x6c, 0x66, 0x5f, 0x66,
	0x10, 0x02, 0x42, 0x11, 0x5a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_network_entity_proto_rawDescOnce sync.Once
	file_internal_protos_network_entity_proto_rawDescData = file_internal_protos_network_entity_proto_rawDesc
)

func file_internal_protos_network_entity_proto_rawDescGZIP() []byte {
	file_internal_protos_network_entity_proto_rawDescOnce.Do(func() {
		file_internal_protos_network_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_network_entity_proto_rawDescData)
	})
	return file_internal_protos_network_entity_proto_rawDescData
}

var file_internal_protos_network_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protos_network_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_protos_network_entity_proto_goTypes = []any{
	(Skin)(0),                  // 0: protos.Skin
	(*NetworkEntity)(nil),      // 1: protos.NetworkEntity
	(*Transform)(nil),          // 2: protos.Transform
	(*Physics)(nil),            // 3: protos.Physics
	(*PatchNetworkEntity)(nil), // 4: protos.PatchNetworkEntity
	(*PatchPhysics)(nil),       // 5: protos.PatchPhysics
	(*PatchTransform)(nil),     // 6: protos.PatchTransform
	(*Vector2)(nil),            // 7: protos.Vector2
}
var file_internal_protos_network_entity_proto_depIdxs = []int32{
	2,  // 0: protos.NetworkEntity.transform:type_name -> protos.Transform
	3,  // 1: protos.NetworkEntity.physics:type_name -> protos.Physics
	7,  // 2: protos.Transform.position:type_name -> protos.Vector2
	7,  // 3: protos.Transform.Scale:type_name -> protos.Vector2
	7,  // 4: protos.Physics.velocity:type_name -> protos.Vector2
	7,  // 5: protos.Physics.position:type_name -> protos.Vector2
	6,  // 6: protos.PatchNetworkEntity.transform:type_name -> protos.PatchTransform
	5,  // 7: protos.PatchNetworkEntity.physics:type_name -> protos.PatchPhysics
	7,  // 8: protos.PatchPhysics.velocity:type_name -> protos.Vector2
	7,  // 9: protos.PatchPhysics.position:type_name -> protos.Vector2
	7,  // 10: protos.PatchTransform.position:type_name -> protos.Vector2
	7,  // 11: protos.PatchTransform.Scale:type_name -> protos.Vector2
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_protos_network_entity_proto_init() }
func file_internal_protos_network_entity_proto_init() {
	if File_internal_protos_network_entity_proto != nil {
		return
	}
	file_internal_protos_utils_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_network_entity_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NetworkEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_network_entity_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Transform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_network_entity_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Physics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_network_entity_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PatchNetworkEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_network_entity_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PatchPhysics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_network_entity_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PatchTransform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_protos_network_entity_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_protos_network_entity_proto_msgTypes[4].OneofWrappers = []any{}
	file_internal_protos_network_entity_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_network_entity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protos_network_entity_proto_goTypes,
		DependencyIndexes: file_internal_protos_network_entity_proto_depIdxs,
		EnumInfos:         file_internal_protos_network_entity_proto_enumTypes,
		MessageInfos:      file_internal_protos_network_entity_proto_msgTypes,
	}.Build()
	File_internal_protos_network_entity_proto = out.File
	file_internal_protos_network_entity_proto_rawDesc = nil
	file_internal_protos_network_entity_proto_goTypes = nil
	file_internal_protos_network_entity_proto_depIdxs = nil
}
