// Code generated by component generator; DO NOT EDIT.

package stdcomponents

import (
	"gomp/pkg/ecs"
)

const (
	InvalidComponentId ecs.ComponentId = iota
	AABBComponentId
	AnimationPlayerComponentId
	AnimationStateComponentId
	BvhComponentComponentId
	BvhTreeComponentId
	CameraComponentId
	BoxColliderComponentId
	CircleColliderComponentId
	PolygonColliderComponentId
	GenericColliderComponentId
	ColliderSleepStateComponentId
	CollisionCellComponentId
	CollisionChunkComponentId
	CollisionGridMemberComponentId
	CollisionGridComponentId
	CollisionComponentId
	FlipComponentId
	FrameBuffer2DComponentId
	NetworkComponentId
	TexturePositionSmoothComponentId
	PositionComponentId
	RenderOrderComponentId
	RenderVisibleComponentId
	RenderableComponentId
	RigidBodyComponentId
	RLTextureProComponentId
	RotationComponentId
	ScaleComponentId
	SpatialHashComponentId
	SpriteMatrixComponentId
	SpriteSheetComponentId
	SpriteComponentId
	TintComponentId
	Transform2dComponentId
	VelocityComponentId
	YSortComponentId
	StdLastComponentId
)
