// Code generated by componentgen; DO NOT EDIT.

package stdcomponents

import (
	"gomp/pkg/ecs"
)

type AABBComponentManager = ecs.ComponentManager[AABB]

func NewAABBComponentManager() AABBComponentManager {
	return ecs.NewComponentManager[AABB](AABBComponentId)
}

type AnimationPlayerComponentManager = ecs.ComponentManager[AnimationPlayer]

func NewAnimationPlayerComponentManager() AnimationPlayerComponentManager {
	return ecs.NewComponentManager[AnimationPlayer](AnimationPlayerComponentId)
}

type AnimationStateComponentManager = ecs.ComponentManager[AnimationState]

func NewAnimationStateComponentManager() AnimationStateComponentManager {
	return ecs.NewComponentManager[AnimationState](AnimationStateComponentId)
}

type BvhComponentComponentManager = ecs.ComponentManager[BvhComponent]

func NewBvhComponentComponentManager() BvhComponentComponentManager {
	return ecs.NewComponentManager[BvhComponent](BvhComponentComponentId)
}

type BvhTreeComponentManager = ecs.ComponentManager[BvhTree]

func NewBvhTreeComponentManager() BvhTreeComponentManager {
	return ecs.NewComponentManager[BvhTree](BvhTreeComponentId)
}

type CameraComponentManager = ecs.ComponentManager[Camera]

func NewCameraComponentManager() CameraComponentManager {
	return ecs.NewComponentManager[Camera](CameraComponentId)
}

type BoxColliderComponentManager = ecs.ComponentManager[BoxCollider]

func NewBoxColliderComponentManager() BoxColliderComponentManager {
	return ecs.NewComponentManager[BoxCollider](BoxColliderComponentId)
}

type CircleColliderComponentManager = ecs.ComponentManager[CircleCollider]

func NewCircleColliderComponentManager() CircleColliderComponentManager {
	return ecs.NewComponentManager[CircleCollider](CircleColliderComponentId)
}

type PolygonColliderComponentManager = ecs.ComponentManager[PolygonCollider]

func NewPolygonColliderComponentManager() PolygonColliderComponentManager {
	return ecs.NewComponentManager[PolygonCollider](PolygonColliderComponentId)
}

type GenericColliderComponentManager = ecs.ComponentManager[GenericCollider]

func NewGenericColliderComponentManager() GenericColliderComponentManager {
	return ecs.NewComponentManager[GenericCollider](GenericColliderComponentId)
}

type ColliderSleepStateComponentManager = ecs.ComponentManager[ColliderSleepState]

func NewColliderSleepStateComponentManager() ColliderSleepStateComponentManager {
	return ecs.NewComponentManager[ColliderSleepState](ColliderSleepStateComponentId)
}

type CollisionCellComponentManager = ecs.ComponentManager[CollisionCell]

func NewCollisionCellComponentManager() CollisionCellComponentManager {
	return ecs.NewComponentManager[CollisionCell](CollisionCellComponentId)
}

type CollisionChunkComponentManager = ecs.ComponentManager[CollisionChunk]

func NewCollisionChunkComponentManager() CollisionChunkComponentManager {
	return ecs.NewComponentManager[CollisionChunk](CollisionChunkComponentId)
}

type CollisionGridMemberComponentManager = ecs.ComponentManager[CollisionGridMember]

func NewCollisionGridMemberComponentManager() CollisionGridMemberComponentManager {
	return ecs.NewComponentManager[CollisionGridMember](CollisionGridMemberComponentId)
}

type CollisionGridComponentManager = ecs.ComponentManager[CollisionGrid]

func NewCollisionGridComponentManager() CollisionGridComponentManager {
	return ecs.NewComponentManager[CollisionGrid](CollisionGridComponentId)
}

type CollisionComponentManager = ecs.ComponentManager[Collision]

func NewCollisionComponentManager() CollisionComponentManager {
	return ecs.NewComponentManager[Collision](CollisionComponentId)
}

type FlipComponentManager = ecs.ComponentManager[Flip]

func NewFlipComponentManager() FlipComponentManager {
	return ecs.NewComponentManager[Flip](FlipComponentId)
}

type FrameBuffer2DComponentManager = ecs.ComponentManager[FrameBuffer2D]

func NewFrameBuffer2DComponentManager() FrameBuffer2DComponentManager {
	return ecs.NewComponentManager[FrameBuffer2D](FrameBuffer2DComponentId)
}

type NetworkComponentManager = ecs.ComponentManager[Network]

func NewNetworkComponentManager() NetworkComponentManager {
	return ecs.NewComponentManager[Network](NetworkComponentId)
}

type TexturePositionSmoothComponentManager = ecs.ComponentManager[TexturePositionSmooth]

func NewTexturePositionSmoothComponentManager() TexturePositionSmoothComponentManager {
	return ecs.NewComponentManager[TexturePositionSmooth](TexturePositionSmoothComponentId)
}

type PositionComponentManager = ecs.ComponentManager[Position]

func NewPositionComponentManager() PositionComponentManager {
	return ecs.NewComponentManager[Position](PositionComponentId)
}

type RenderOrderComponentManager = ecs.ComponentManager[RenderOrder]

func NewRenderOrderComponentManager() RenderOrderComponentManager {
	return ecs.NewComponentManager[RenderOrder](RenderOrderComponentId)
}

type RenderVisibleComponentManager = ecs.ComponentManager[RenderVisible]

func NewRenderVisibleComponentManager() RenderVisibleComponentManager {
	return ecs.NewComponentManager[RenderVisible](RenderVisibleComponentId)
}

type RenderableComponentManager = ecs.ComponentManager[Renderable]

func NewRenderableComponentManager() RenderableComponentManager {
	return ecs.NewComponentManager[Renderable](RenderableComponentId)
}

type RigidBodyComponentManager = ecs.ComponentManager[RigidBody]

func NewRigidBodyComponentManager() RigidBodyComponentManager {
	return ecs.NewComponentManager[RigidBody](RigidBodyComponentId)
}

type RLTextureProComponentManager = ecs.ComponentManager[RLTexturePro]

func NewRLTextureProComponentManager() RLTextureProComponentManager {
	return ecs.NewComponentManager[RLTexturePro](RLTextureProComponentId)
}

type RotationComponentManager = ecs.ComponentManager[Rotation]

func NewRotationComponentManager() RotationComponentManager {
	return ecs.NewComponentManager[Rotation](RotationComponentId)
}

type ScaleComponentManager = ecs.ComponentManager[Scale]

func NewScaleComponentManager() ScaleComponentManager {
	return ecs.NewComponentManager[Scale](ScaleComponentId)
}

type SpatialHashComponentManager = ecs.ComponentManager[SpatialHash]

func NewSpatialHashComponentManager() SpatialHashComponentManager {
	return ecs.NewComponentManager[SpatialHash](SpatialHashComponentId)
}

type SpriteMatrixComponentManager = ecs.SharedComponentManager[SpriteMatrix]

func NewSpriteMatrixComponentManager() SpriteMatrixComponentManager {
	return ecs.NewSharedComponentManager[SpriteMatrix](SpriteMatrixComponentId)
}

type SpriteSheetComponentManager = ecs.ComponentManager[SpriteSheet]

func NewSpriteSheetComponentManager() SpriteSheetComponentManager {
	return ecs.NewComponentManager[SpriteSheet](SpriteSheetComponentId)
}

type SpriteComponentManager = ecs.ComponentManager[Sprite]

func NewSpriteComponentManager() SpriteComponentManager {
	return ecs.NewComponentManager[Sprite](SpriteComponentId)
}

type TintComponentManager = ecs.ComponentManager[Tint]

func NewTintComponentManager() TintComponentManager {
	return ecs.NewComponentManager[Tint](TintComponentId)
}

type Transform2dComponentManager = ecs.ComponentManager[Transform2d]

func NewTransform2dComponentManager() Transform2dComponentManager {
	return ecs.NewComponentManager[Transform2d](Transform2dComponentId)
}

type VelocityComponentManager = ecs.ComponentManager[Velocity]

func NewVelocityComponentManager() VelocityComponentManager {
	return ecs.NewComponentManager[Velocity](VelocityComponentId)
}

type YSortComponentManager = ecs.ComponentManager[YSort]

func NewYSortComponentManager() YSortComponentManager {
	return ecs.NewComponentManager[YSort](YSortComponentId)
}
