// Code generated by component generator; DO NOT EDIT.

package components

import (
	"gomp/stdcomponents"
)

const (
	AsteroidSceneManagerComponentId = iota + stdcomponents.StdLastComponentId
	AsteroidTagComponentId
	SoundEffectComponentId
	SpatialAudioComponentId
	BulletTagComponentId
	ControllerComponentId
	HpComponentId
	SpaceSpawnerTagComponentId
	SpaceshipIntentComponentId
	PlayerTagComponentId
	TextureCircleComponentId
	TextureRectComponentId
	WallComponentId
	WeaponComponentId
)
