// Code generated by componentgen; DO NOT EDIT.

package components

import (
	"gomp/pkg/ecs"
)

type AsteroidSceneManagerComponentManager = ecs.ComponentManager[AsteroidSceneManager]

func NewAsteroidSceneManagerComponentManager() AsteroidSceneManagerComponentManager {
	return ecs.NewComponentManager[AsteroidSceneManager](AsteroidSceneManagerComponentId)
}

type AsteroidTagComponentManager = ecs.ComponentManager[AsteroidTag]

func NewAsteroidTagComponentManager() AsteroidTagComponentManager {
	return ecs.NewComponentManager[AsteroidTag](AsteroidTagComponentId)
}

type SoundEffectComponentManager = ecs.ComponentManager[SoundEffect]

func NewSoundEffectComponentManager() SoundEffectComponentManager {
	return ecs.NewComponentManager[SoundEffect](SoundEffectComponentId)
}

type SpatialAudioComponentManager = ecs.ComponentManager[SpatialAudio]

func NewSpatialAudioComponentManager() SpatialAudioComponentManager {
	return ecs.NewComponentManager[SpatialAudio](SpatialAudioComponentId)
}

type BulletTagComponentManager = ecs.ComponentManager[BulletTag]

func NewBulletTagComponentManager() BulletTagComponentManager {
	return ecs.NewComponentManager[BulletTag](BulletTagComponentId)
}

type ControllerComponentManager = ecs.ComponentManager[Controller]

func NewControllerComponentManager() ControllerComponentManager {
	return ecs.NewComponentManager[Controller](ControllerComponentId)
}

type HpComponentManager = ecs.ComponentManager[Hp]

func NewHpComponentManager() HpComponentManager {
	return ecs.NewComponentManager[Hp](HpComponentId)
}

type SpaceSpawnerTagComponentManager = ecs.ComponentManager[SpaceSpawnerTag]

func NewSpaceSpawnerTagComponentManager() SpaceSpawnerTagComponentManager {
	return ecs.NewComponentManager[SpaceSpawnerTag](SpaceSpawnerTagComponentId)
}

type SpaceshipIntentComponentManager = ecs.ComponentManager[SpaceshipIntent]

func NewSpaceshipIntentComponentManager() SpaceshipIntentComponentManager {
	return ecs.NewComponentManager[SpaceshipIntent](SpaceshipIntentComponentId)
}

type PlayerTagComponentManager = ecs.ComponentManager[PlayerTag]

func NewPlayerTagComponentManager() PlayerTagComponentManager {
	return ecs.NewComponentManager[PlayerTag](PlayerTagComponentId)
}

type TextureCircleComponentManager = ecs.ComponentManager[TextureCircle]

func NewTextureCircleComponentManager() TextureCircleComponentManager {
	return ecs.NewComponentManager[TextureCircle](TextureCircleComponentId)
}

type TextureRectComponentManager = ecs.ComponentManager[TextureRect]

func NewTextureRectComponentManager() TextureRectComponentManager {
	return ecs.NewComponentManager[TextureRect](TextureRectComponentId)
}

type WallComponentManager = ecs.ComponentManager[Wall]

func NewWallComponentManager() WallComponentManager {
	return ecs.NewComponentManager[Wall](WallComponentId)
}

type WeaponComponentManager = ecs.ComponentManager[Weapon]

func NewWeaponComponentManager() WeaponComponentManager {
	return ecs.NewComponentManager[Weapon](WeaponComponentId)
}
