name: Gosec Security Check

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  gosec-security-analysis:
    runs-on: 'ubuntu-latest'
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Gosec Security Scanner
        run: |
          gosec -exclude=G404 -fmt=sarif -out=gosec-results.sarif ./... || true

      - name: Upload SARIF report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec-results.sarif