name: Master Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        go-version: [ '1.24.0' ]
    uses: ./.github/workflows/go_ci.yml
    with:
      go-version: ${{ matrix.go-version }}
      os: ${{ matrix.os }}

  security-analysis:
    uses: ./.github/workflows/gosec_security_check.yml
    with:
      go-version: '1.24.0'